// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgtmdfiyfzphsexsjaob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZndG1kZml5ZnpwaHNleHNqYW9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5Nzg2MDIsImV4cCI6MjA2OTU1NDYwMn0.BleQm4OnoNAnp9VyzF2pRMF7ZNAqXaY53b7f5_3sWao";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});